version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "installing something intreasting"
  pre_build:
    commands:
      - echo "we are in the pre build phase"
      - npm install
      - npm install pm2@latest -g
  build:
    commands:
      - echo "we are in the build block"
      - pm2 start index.js --name node_server
      - echo "we will run some tests"
      - grep -Fq "Cities" index.js
      - pm2 stop node_server
  post_build:
    commands:
      - echo "we are in the post build phase"
