version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "installing something"
  pre_build:
    commands:
      - echo "we are in the pre build phase"
      - npm install
  build:
    commands:
      - echo "we are in the build block"
      - npm start index.js
      - echo "we will run some tests"
      - grep -Fq "Cities" index.js
  post_build:
    commands:
      - echo "we are in the post build phase"
